package com.sbtools.systeminfo;

import com.sbtools.util.AppInfo;

import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

/**
 * Pure report rendering for System Information snapshots.
 *
 * <p>Extracted from {@code SystemInfoTabView} (v1.2.8, 1700+ line god-class) so
 * plain-text / HTML exports share one implementation and can be unit-tested
 * without JavaFX. All methods are null-tolerant and preserve the legacy section
 * order: OS, CPU, GPU, RAM, Storage, Motherboard, BIOS, Network, Audio,
 * Battery, Temperatures, Others, USB, Monitors, Printers, Warnings.
 *
 * <p>v3.1 additions (backward compatible): report header with
 * {@code generatedAt / appVersion / payload version / collectedAt / timings},
 * per-tab plain-text snippets for "Copy visible tab", and HTML TOC anchors.
 */
public final class SystemInfoReportGenerator {

    private static final DateTimeFormatter HEADER_FMT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss").withZone(ZoneId.systemDefault());

    private SystemInfoReportGenerator() {
    }

    // ── Public entry points ──────────────────────────────────────────────

    public static String generatePlainTextReport(SystemInfoData data) {
        return generatePlainTextReport(data, null);
    }

    /**
     * @param adminHint null when unknown; otherwise rendered as "Yes/No" in the header.
     */
    public static String generatePlainTextReport(SystemInfoData data, Boolean adminHint) {
        StringBuilder sb = new StringBuilder();
        sb.append("=== System Information ===\n");
        sb.append("Generated by ").append(AppInfo.DISPLAY_NAME)
                .append(" v").append(AppInfo.getVersion()).append("\n");
        sb.append("Generated at: ").append(HEADER_FMT.format(Instant.now())).append("\n");
        if (data != null) {
            if (data.version() != null && !data.version().isBlank()) {
                sb.append("Payload version: ").append(data.version()).append("\n");
            }
            if (data.collectedAt() != null && !data.collectedAt().isBlank()) {
                sb.append("Collected at: ").append(data.collectedAt()).append("\n");
            }
            if (adminHint != null) {
                sb.append("Running as admin: ").append(adminHint ? "Yes" : "No").append("\n");
            }
            appendTimingsText(sb, data.timings());
        }
        sb.append("\n");

        if (data == null) {
            sb.append("(no data)\n");
            return sb.toString();
        }

        if (data.os() != null) {
            sb.append("--- Operating System ---\n");
            appendField(sb, "OS", data.os().name());
            appendField(sb, "Version", data.os().version());
            appendField(sb, "Build", data.os().buildNumber());
            appendField(sb, "Architecture", data.os().architecture());
            appendField(sb, "Computer Name", data.os().computerName());
            appendField(sb, "Install Date", data.os().installDate());
            appendField(sb, "Last Boot", data.os().lastBoot());
            appendField(sb, "Serial Number", data.os().serialNumber());
            sb.append("\n");
        }

        if (data.cpu() != null) {
            sb.append("--- CPU ---\n");
            appendField(sb, "Name", data.cpu().name());
            appendField(sb, "Manufacturer", data.cpu().manufacturer());
            appendField(sb, "Architecture", data.cpu().architecture());
            appendField(sb, "Socket", data.cpu().socket());
            sb.append("Cores: ").append(data.cpu().cores()).append("\n");
            sb.append("Threads: ").append(data.cpu().logicalCpus()).append("\n");
            appendField(sb, "Base Clock", data.cpu().formatBaseClock());
            appendField(sb, "Current Clock", data.cpu().formatCurrentClock());
            appendField(sb, "L2 Cache", data.cpu().formatL2Cache());
            appendField(sb, "L3 Cache", data.cpu().formatL3Cache());
            appendField(sb, "Voltage", data.cpu().voltage());
            sb.append("\n");
        }

        if (data.gpu() != null) {
            for (int i = 0; i < data.gpu().size(); i++) {
                GpuInfo gpu = data.gpu().get(i);
                sb.append("--- GPU").append(data.gpu().size() > 1 ? " " + (i + 1) : "").append(" ---\n");
                appendField(sb, "Name", gpu.name());
                appendField(sb, "Manufacturer", gpu.manufacturer());
                appendField(sb, "VRAM", gpu.formatVram());
                appendField(sb, "Memory Type", gpu.memoryType());
                appendField(sb, "Driver Version", gpu.driverVersion());
                appendField(sb, "Driver Date", gpu.driverDate());
                appendField(sb, "Resolution", gpu.resolution());
                sb.append("\n");
            }
        }

        if (data.ram() != null) {
            sb.append("--- RAM ---\n");
            appendField(sb, "Total", data.ram().formatTotal());
            appendField(sb, "Channel", data.ram().channel());
            if (data.ram().sticks() != null) {
                for (int i = 0; i < data.ram().sticks().size(); i++) {
                    RamInfo.RamStick stick = data.ram().sticks().get(i);
                    sb.append("  Slot ").append(i + 1).append(": ").append(stick.formatCapacity())
                            .append(" ").append(nvl(stick.memoryType())).append(" ").append(stick.formatSpeed())
                            .append(" ").append(nvl(stick.manufacturer())).append("\n");
                }
            }
            sb.append("\n");
        }

        if (data.storage() != null) {
            sb.append("--- Storage ---\n");
            if (data.storage().disks() != null) {
                for (int i = 0; i < data.storage().disks().size(); i++) {
                    StorageInfo.Disk disk = data.storage().disks().get(i);
                    sb.append("Disk ").append(i + 1).append(": ").append(nvl(disk.model()))
                            .append(" (").append(disk.formatSize()).append(") ").append(nvl(disk.interfaceType()))
                            .append(" [").append(nvl(disk.mediaType())).append("]\n");
                    if (data.storage().partitions() != null) {
                        final int diskIdx = i;
                        data.storage().partitions().stream()
                                .filter(p -> p.diskIndex() == diskIdx)
                                .forEach(part -> sb.append("  ").append(nvl(part.deviceID())).append(": ").append(nvl(part.volumeName()))
                                        .append(" ").append(nvl(part.fsType()))
                                        .append(" ").append(part.formatSize())
                                        .append(" (").append(String.format("%.1f%% used", part.usagePercent())).append(")\n"));
                    }
                }
            }
            if (data.storage().nvmes() != null && !data.storage().nvmes().isEmpty()) {
                sb.append("NVMe Drives:\n");
                for (StorageInfo.Nvme nvme : data.storage().nvmes()) {
                    sb.append("  Serial: ").append(nvme.serialNumber())
                            .append(" | Media: ").append(nvme.mediaType())
                            .append(" | Bus: ").append(nvme.busType()).append("\n");
                }
            }
            sb.append("\n");
        }

        if (data.motherboard() != null) {
            sb.append("--- Motherboard ---\n");
            appendField(sb, "Manufacturer", data.motherboard().manufacturer());
            appendField(sb, "Model", data.motherboard().model());
            appendField(sb, "Version", data.motherboard().version());
            appendField(sb, "Chipset", data.motherboard().chipset());
            sb.append("\n");
        }

        if (data.bios() != null) {
            sb.append("--- BIOS ---\n");
            appendField(sb, "Manufacturer", data.bios().manufacturer());
            appendField(sb, "Version", data.bios().version());
            appendField(sb, "Release Date", data.bios().releaseDate());
            appendField(sb, "SMBIOS", data.bios().formatSmbios());
            sb.append("\n");
        }

        if (data.networkAdapters() != null && !data.networkAdapters().isEmpty()) {
            sb.append("--- Network Adapters ---\n");
            for (NetworkAdapterInfo na : data.networkAdapters()) {
                sb.append(nvl(na.name())).append(" (").append(nvl(na.status())).append(")\n");
                appendField(sb, "  Speed", na.speed());
                appendField(sb, "  MAC", na.macAddress());
                sb.append("  IP: ").append(na.formatIpAddresses()).append("\n");
                sb.append("  DHCP: ").append(na.dhcpEnabled() ? "Yes" : "No").append("\n\n");
            }
        }

        if (data.audioDevices() != null && !data.audioDevices().isEmpty()) {
            sb.append("--- Audio Devices ---\n");
            for (AudioDeviceInfo audio : data.audioDevices()) {
                sb.append(nvl(audio.name())).append(" - ").append(nvl(audio.manufacturer()))
                        .append(" (").append(nvl(audio.status())).append(")\n");
            }
            sb.append("\n");
        }

        if (data.battery() != null) {
            BatteryInfo batt = data.battery();
            sb.append("--- Battery ---\n");
            appendField(sb, "Name", batt.name());
            sb.append("Charge: ").append(batt.formatChargeLevel()).append("\n");
            appendField(sb, "Status", batt.status());
            appendField(sb, "Chemistry", batt.chemistry());
            sb.append("Remaining: ").append(batt.formatRemainingCapacity()).append("\n\n");
        }

        if (data.temperatures() != null && !data.temperatures().isEmpty()) {
            sb.append("--- Temperatures ---\n");
            for (TemperatureInfo temp : data.temperatures()) {
                sb.append(temp.zoneName()).append(": ").append(temp.formatTemperature()).append("\n");
            }
            sb.append("\n");
        }

        if (data.others() != null && !data.others().isEmpty()) {
            sb.append("--- Other Devices (").append(data.others().size()).append(") ---\n");
            for (OtherDevice dev : data.others()) {
                sb.append(nvl(dev.name())).append(" [").append(nvl(dev.deviceClass())).append("]\n");
            }
            sb.append("\n");
        }

        if (data.usbDevices() != null && !data.usbDevices().isEmpty()) {
            sb.append("--- USB Devices ---\n");
            for (UsbDeviceInfo usb : data.usbDevices()) {
                sb.append(nvl(usb.name())).append(" (").append(nvl(usb.status())).append(")\n");
                appendField(sb, "  Manufacturer", usb.manufacturer());
            }
            sb.append("\n");
        }

        if (data.monitors() != null && !data.monitors().isEmpty()) {
            sb.append("--- Monitors ---\n");
            for (MonitorInfo mon : data.monitors()) {
                sb.append(nvl(mon.name())).append(" - ").append(nvl(mon.resolution())).append("\n");
                appendField(sb, "  Manufacturer", mon.manufacturer());
            }
            sb.append("\n");
        }

        if (data.printers() != null && !data.printers().isEmpty()) {
            sb.append("--- Printers ---\n");
            for (PrinterInfo printer : data.printers()) {
                sb.append(nvl(printer.name())).append(" (").append(nvl(printer.status())).append(")\n");
                appendField(sb, "  Driver", printer.driver());
                appendField(sb, "  Port", printer.port());
            }
            sb.append("\n");
        }

        if (data.warnings() != null && !data.warnings().isEmpty()) {
            sb.append("--- Warnings ---\n");
            for (String w : data.warnings()) {
                sb.append("! ").append(w).append("\n");
            }
        }

        return sb.toString();
    }

    /**
     * Plain-text snippet for a single visible tab (used by "Copy visible tab").
     * Tab names match {@code SystemInfoTabView} tab titles.
     */
    public static String generateSectionText(SystemInfoData data, String tabName) {
        if (data == null || tabName == null) {
            return "";
        }
        String full = generatePlainTextReport(data);
        String header = switch (tabName) {
            case "Overview" -> null; // full summary
            case "CPU" -> "--- CPU ---";
            case "GPU" -> "--- GPU";
            case "RAM" -> "--- RAM ---";
            case "OS" -> "--- Operating System ---";
            case "Storage" -> "--- Storage ---";
            case "Motherboard" -> "--- Motherboard ---";
            case "Network" -> "--- Network Adapters ---";
            case "Audio" -> "--- Audio Devices ---";
            case "Battery" -> "--- Battery ---";
            case "Temperatures" -> "--- Temperatures ---";
            case "Others" -> "--- Other Devices";
            case "USB Devices" -> "--- USB Devices ---";
            case "Monitors" -> "--- Monitors ---";
            case "Printers" -> "--- Printers ---";
            case "Warnings" -> "--- Warnings ---";
            default -> null;
        };
        if (header == null) {
            return full;
        }
        int start = full.indexOf(header);
        if (start < 0) {
            return tabName + ": (no data)\n";
        }
        int end = full.indexOf("\n--- ", start + header.length());
        if (end < 0) {
            end = full.length();
        }
        return full.substring(start, end).strip() + "\n";
    }

    public static String generateHtmlReport(SystemInfoData data) {
        return generateHtmlReport(data, null);
    }

    public static String generateHtmlReport(SystemInfoData data, Boolean adminHint) {
        StringBuilder html = new StringBuilder();
        html.append("<!DOCTYPE html><html><head><meta charset=\"UTF-8\">");
        html.append("<title>System Information - ").append(escapeHtml(AppInfo.DISPLAY_NAME)).append("</title>");
        html.append("<style>");
        html.append("body{font-family:'Segoe UI',sans-serif;background:#1e1f29;color:#f8f8f2;margin:24px;}");
        html.append("h1{color:#50fa7b;border-bottom:2px solid #44475a;padding-bottom:8px;}");
        html.append("h2{color:#8be9fd;margin-top:24px;}");
        html.append("table{border-collapse:collapse;width:100%;margin:8px 0 20px 0;}");
        html.append("td{padding:6px 12px;border-bottom:1px solid #44475a;}");
        html.append("td:first-child{color:#6272a4;font-weight:bold;width:180px;}");
        html.append("tr:nth-child(even){background:#21222c;}");
        html.append(".warning{color:#ffb86c;background:#3d2e1a;padding:8px;border-radius:4px;margin:8px 0;}");
        html.append(".meta{color:#6272a4;font-size:12px;}");
        html.append(".toc{margin:12px 0 20px 0;}");
        html.append(".toc a{color:#8be9fd;text-decoration:none;margin-right:12px;}");
        html.append("</style></head><body>");
        html.append("<h1>System Information</h1>");
        html.append("<p class=\"meta\">Generated by ").append(escapeHtml(AppInfo.DISPLAY_NAME))
                .append(" v").append(escapeHtml(AppInfo.getVersion()))
                .append(" at ").append(escapeHtml(HEADER_FMT.format(Instant.now())));
        if (data != null && data.version() != null && !data.version().isBlank()) {
            html.append(" | payload v").append(escapeHtml(data.version()));
        }
        if (data != null && data.collectedAt() != null && !data.collectedAt().isBlank()) {
            html.append(" | collected ").append(escapeHtml(data.collectedAt()));
        }
        if (adminHint != null) {
            html.append(" | admin: ").append(adminHint ? "yes" : "no");
        }
        html.append("</p>");
        if (data != null && data.timings() != null && !data.timings().isEmpty()) {
            html.append("<p class=\"meta\">Timings (ms): ");
            boolean first = true;
            for (Map.Entry<String, Long> e : data.timings().entrySet()) {
                if (!first) {
                    html.append(", ");
                }
                first = false;
                html.append(escapeHtml(e.getKey())).append("=").append(e.getValue() == null ? 0 : e.getValue());
            }
            html.append("</p>");
        }
        // TOC anchors (print-friendly, no JS)
        html.append("<div class=\"toc\">");
        String[] toc = {"OS", "CPU", "GPU", "RAM", "Storage", "Motherboard", "BIOS",
                "Network", "Audio", "Battery", "Temperatures", "USB", "Monitors", "Printers", "Warnings"};
        for (String t : toc) {
            html.append("<a href=\"#sec-").append(t).append("\">").append(t).append("</a>");
        }
        html.append("</div>");

        if (data == null) {
            html.append("<p>(no data)</p></body></html>");
            return html.toString();
        }

        if (data.os() != null) {
            html.append("<h2 id=\"sec-OS\">Operating System</h2><table>");
            html.append(row("OS", data.os().name()));
            html.append(row("Version", data.os().version()));
            html.append(row("Build", data.os().buildNumber()));
            html.append(row("Architecture", data.os().architecture()));
            html.append(row("Computer Name", data.os().computerName()));
            html.append(row("Install Date", data.os().installDate()));
            html.append(row("Last Boot", data.os().lastBoot()));
            html.append(row("Serial Number", data.os().serialNumber()));
            html.append("</table>");
        }

        if (data.cpu() != null) {
            html.append("<h2 id=\"sec-CPU\">CPU</h2><table>");
            html.append(row("Name", data.cpu().name()));
            html.append(row("Manufacturer", data.cpu().manufacturer()));
            html.append(row("Architecture", data.cpu().architecture()));
            html.append(row("Socket", data.cpu().socket()));
            html.append(row("Cores", String.valueOf(data.cpu().cores())));
            html.append(row("Threads", String.valueOf(data.cpu().logicalCpus())));
            html.append(row("Base Clock", data.cpu().formatBaseClock()));
            html.append(row("Current Clock", data.cpu().formatCurrentClock()));
            html.append(row("L2 Cache", data.cpu().formatL2Cache()));
            html.append(row("L3 Cache", data.cpu().formatL3Cache()));
            html.append(row("Voltage", data.cpu().voltage()));
            html.append("</table>");
        }

        if (data.gpu() != null) {
            for (int i = 0; i < data.gpu().size(); i++) {
                GpuInfo gpu = data.gpu().get(i);
                html.append("<h2 id=\"sec-GPU\">GPU").append(data.gpu().size() > 1 ? " " + (i + 1) : "").append("</h2><table>");
                html.append(row("Name", gpu.name()));
                html.append(row("Manufacturer", gpu.manufacturer()));
                html.append(row("VRAM", gpu.formatVram()));
                html.append(row("Memory Type", gpu.memoryType()));
                html.append(row("Driver Version", gpu.driverVersion()));
                html.append(row("Driver Date", gpu.driverDate()));
                html.append(row("Resolution", gpu.resolution()));
                html.append("</table>");
            }
        }

        if (data.ram() != null) {
            html.append("<h2 id=\"sec-RAM\">RAM</h2><table>");
            html.append(row("Total", data.ram().formatTotal()));
            html.append(row("Channel", data.ram().channel()));
            html.append("</table>");
            if (data.ram().sticks() != null) {
                for (int i = 0; i < data.ram().sticks().size(); i++) {
                    RamInfo.RamStick stick = data.ram().sticks().get(i);
                    html.append("<h3>Slot ").append(i + 1).append("</h3><table>");
                    html.append(row("Capacity", stick.formatCapacity()));
                    html.append(row("Type", stick.memoryType()));
                    html.append(row("Speed", stick.formatSpeed()));
                    html.append(row("Manufacturer", stick.manufacturer()));
                    html.append(row("Part Number", stick.partNumber()));
                    html.append("</table>");
                }
            }
        }

        if (data.storage() != null && data.storage().disks() != null) {
            html.append("<h2 id=\"sec-Storage\">Storage</h2>");
            for (int i = 0; i < data.storage().disks().size(); i++) {
                StorageInfo.Disk disk = data.storage().disks().get(i);
                html.append("<h3>Disk ").append(i + 1).append("</h3><table>");
                html.append(row("Model", disk.model()));
                html.append(row("Manufacturer", disk.manufacturer()));
                html.append(row("Size", disk.formatSize()));
                html.append(row("Media Type", disk.mediaType()));
                html.append(row("Interface", disk.interfaceType()));
                html.append(row("Serial", disk.serialNumber()));
                html.append(row("Partitions", String.valueOf(disk.partitions())));
                html.append("</table>");

                if (data.storage().partitions() != null) {
                    final int diskIdx = i;
                    List<StorageInfo.Partition> diskParts = data.storage().partitions().stream()
                            .filter(p -> p.diskIndex() == diskIdx)
                            .toList();
                    if (!diskParts.isEmpty()) {
                        html.append("<h4>Partitions on Disk ").append(i + 1).append("</h4><table>");
                        for (StorageInfo.Partition part : diskParts) {
                            html.append("<tr><td>").append(escapeHtml(part.deviceID())).append("</td><td>")
                                    .append(escapeHtml(part.volumeName())).append(" | ")
                                    .append(escapeHtml(part.fsType())).append(" | ")
                                    .append(part.formatSize()).append(" | ")
                                    .append(String.format("%.1f%% used", part.usagePercent()))
                                    .append("</td></tr>");
                        }
                        html.append("</table>");
                    }
                }
            }

            List<StorageInfo.Partition> unassigned = data.storage().partitions() != null
                    ? data.storage().partitions().stream().filter(p -> p.diskIndex() < 0).toList()
                    : List.of();
            if (!unassigned.isEmpty()) {
                html.append("<h3>Other Partitions</h3><table>");
                for (StorageInfo.Partition part : unassigned) {
                    html.append("<tr><td>").append(escapeHtml(part.deviceID())).append("</td><td>")
                            .append(escapeHtml(part.volumeName())).append(" | ")
                            .append(escapeHtml(part.fsType())).append(" | ")
                            .append(part.formatSize()).append(" | ")
                            .append(String.format("%.1f%% used", part.usagePercent()))
                            .append("</td></tr>");
                }
                html.append("</table>");
            }
        }

        if (data.storage() != null && data.storage().nvmes() != null && !data.storage().nvmes().isEmpty()) {
            html.append("<h2>NVMe Drives</h2>");
            for (int i = 0; i < data.storage().nvmes().size(); i++) {
                StorageInfo.Nvme nvme = data.storage().nvmes().get(i);
                if (data.storage().nvmes().size() > 1) {
                    html.append("<h3>NVMe ").append(i + 1).append("</h3>");
                }
                html.append("<table>");
                html.append(row("Serial Number", nvme.serialNumber()));
                html.append(row("Media Type", nvme.mediaType()));
                html.append(row("Bus Type", nvme.busType()));
                html.append("</table>");
            }
        }

        if (data.motherboard() != null) {
            html.append("<h2 id=\"sec-Motherboard\">Motherboard</h2><table>");
            html.append(row("Manufacturer", data.motherboard().manufacturer()));
            html.append(row("Model", data.motherboard().model()));
            html.append(row("Version", data.motherboard().version()));
            html.append(row("Chipset", data.motherboard().chipset()));
            html.append("</table>");
        }

        if (data.bios() != null) {
            html.append("<h2 id=\"sec-BIOS\">BIOS</h2><table>");
            html.append(row("Manufacturer", data.bios().manufacturer()));
            html.append(row("Version", data.bios().version()));
            html.append(row("Release Date", data.bios().releaseDate()));
            html.append(row("SMBIOS", data.bios().formatSmbios()));
            html.append("</table>");
        }

        if (data.networkAdapters() != null && !data.networkAdapters().isEmpty()) {
            html.append("<h2 id=\"sec-Network\">Network Adapters</h2>");
            for (NetworkAdapterInfo na : data.networkAdapters()) {
                html.append("<h3>").append(escapeHtml(na.name())).append("</h3><table>");
                html.append(row("Name", na.name()));
                html.append(row("Manufacturer", na.manufacturer()));
                html.append(row("Type", na.adapterType()));
                html.append(row("Speed", na.speed()));
                html.append(row("MAC Address", na.macAddress()));
                html.append(row("IP Addresses", na.formatIpAddresses()));
                html.append(row("DHCP", na.dhcpEnabled() ? "Enabled" : "Disabled"));
                html.append(row("Status", na.status()));
                html.append("</table>");
            }
        }

        if (data.audioDevices() != null && !data.audioDevices().isEmpty()) {
            html.append("<h2 id=\"sec-Audio\">Audio Devices</h2><table>");
            for (AudioDeviceInfo audio : data.audioDevices()) {
                html.append(row("Name", audio.name()));
                html.append(row("Manufacturer", audio.manufacturer()));
                html.append(row("Status", audio.status()));
            }
            html.append("</table>");
        }

        if (data.battery() != null) {
            html.append("<h2 id=\"sec-Battery\">Battery</h2><table>");
            html.append(row("Name", data.battery().name()));
            html.append(row("Charge Level", data.battery().formatChargeLevel()));
            html.append(row("Status", data.battery().status()));
            html.append(row("Chemistry", data.battery().chemistry()));
            html.append(row("Remaining", data.battery().formatRemainingCapacity()));
            html.append("</table>");
        }

        if (data.temperatures() != null && !data.temperatures().isEmpty()) {
            html.append("<h2 id=\"sec-Temperatures\">Temperatures</h2><table>");
            for (TemperatureInfo temp : data.temperatures()) {
                html.append(row(temp.zoneName(), temp.formatTemperature()));
            }
            html.append("</table>");
        }

        if (data.others() != null && !data.others().isEmpty()) {
            html.append("<h2 id=\"sec-Others\">Other Devices (").append(data.others().size()).append(")</h2><table>");
            for (OtherDevice dev : data.others()) {
                html.append(row(nvl(dev.deviceClass()) + " / " + nvl(dev.name()),
                        nvl(dev.manufacturer()) + " " + nvl(dev.status())));
            }
            html.append("</table>");
        }

        if (data.usbDevices() != null && !data.usbDevices().isEmpty()) {
            html.append("<h2 id=\"sec-USB\">USB Devices</h2>");
            for (UsbDeviceInfo usb : data.usbDevices()) {
                html.append("<h3>").append(escapeHtml(usb.name())).append("</h3><table>");
                html.append(row("Name", usb.name()));
                html.append(row("Manufacturer", usb.manufacturer()));
                html.append(row("Device ID", usb.deviceId()));
                html.append(row("Status", usb.status()));
                html.append("</table>");
            }
        }

        if (data.monitors() != null && !data.monitors().isEmpty()) {
            html.append("<h2 id=\"sec-Monitors\">Monitors</h2>");
            for (MonitorInfo mon : data.monitors()) {
                html.append("<h3>").append(escapeHtml(mon.name())).append("</h3><table>");
                html.append(row("Name", mon.name()));
                html.append(row("Manufacturer", mon.manufacturer()));
                html.append(row("Resolution", mon.resolution()));
                html.append(row("Status", mon.status()));
                html.append("</table>");
            }
        }

        if (data.printers() != null && !data.printers().isEmpty()) {
            html.append("<h2 id=\"sec-Printers\">Printers</h2>");
            for (PrinterInfo printer : data.printers()) {
                html.append("<h3>").append(escapeHtml(printer.name())).append("</h3><table>");
                html.append(row("Name", printer.name()));
                html.append(row("Driver", printer.driver()));
                html.append(row("Port", printer.port()));
                html.append(row("Status", printer.status()));
                html.append(row("Shared", printer.shared() ? "Yes" : "No"));
                html.append(row("Default", printer.isDefault() ? "Yes" : "No"));
                html.append("</table>");
            }
        }

        if (data.warnings() != null && !data.warnings().isEmpty()) {
            html.append("<h2 id=\"sec-Warnings\">Warnings</h2>");
            for (String w : data.warnings()) {
                html.append("<div class=\"warning\">").append(escapeHtml(w)).append("</div>");
            }
        }

        html.append("</body></html>");
        return html.toString();
    }

    // ── Helpers ──────────────────────────────────────────────────────────

    private static void appendTimingsText(StringBuilder sb, Map<String, Long> timings) {
        if (timings == null || timings.isEmpty()) {
            return;
        }
        sb.append("Timings (ms): ");
        boolean first = true;
        for (Map.Entry<String, Long> e : timings.entrySet()) {
            if (!first) {
                sb.append(", ");
            }
            first = false;
            sb.append(e.getKey()).append("=").append(e.getValue() == null ? 0 : e.getValue());
        }
        sb.append("\n");
    }

    private static String nvl(String s) {
        return s != null ? s : "";
    }

    private static void appendField(StringBuilder sb, String label, String value) {
        if (value != null && !value.isBlank()) {
            sb.append(label).append(": ").append(value).append("\n");
        }
    }

    private static String row(String label, String value) {
        return "<tr><td>" + escapeHtml(label) + "</td><td>" + escapeHtml(value != null ? value : "") + "</td></tr>";
    }

    private static String escapeHtml(String text) {
        if (text == null) {
            return "";
        }
        return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                .replace("\"", "&quot;").replace("'", "&#39;");
    }
}
